import { PDFDocument } from 'pdf-lib'
import type { FormValueInput, PdfAnnotation } from './pdf-android-types'

// Android PDF platform adapter. The renderer talks to this module through the
// Capacitor bridge; the actual PDF operations stay isolated from the desktop shell.

function appendAnnot(doc: PDFDocument, page: any, ref: any): void {
  const annots = page.node.lookupMaybe('Annots', doc.context.obj([]))
  annots.push(ref)
  page.node.set('Annots', annots)
}

function addAnnotation(doc: PDFDocument, page: any, d: PdfAnnotation): void {
  const rect = d.rect
  const ops: string[] = []
  if (d.kind === 'ink') {
    ops.push('q')
    // line/path drawing is generated by the Android renderer before it reaches this adapter
    ops.push('Q')
  }
  const ap = doc.context.stream(ops.join('\n'), { Type: 'XObject', Subtype: 'Form', BBox: rect })
  const annot = doc.context.obj({
    Type: 'Annot',
    Subtype: d.kind === 'ink' ? 'Ink' : d.kind === 'ellipse' ? 'Circle' : d.kind === 'rect' ? 'Square' : 'Line',
    Rect: rect,
    C: d.color,
    F: 4,
    P: page.ref,
    AP: { N: doc.context.register(ap) },
  })
  appendAnnot(doc, page, doc.context.register(annot))
}

async function applyFormValues(doc: PDFDocument, values: FormValueInput[]): Promise<void> {
  if (!values.length) return
  const form = doc.getForm()
  for (const item of values) {
    try {
      const field = form.getField(item.name) as any
      if (item.kind === 'checkbox' && 'check' in field) {
        if (item.checked) field.check()
        else field.uncheck()
      } else if (item.value !== undefined && 'setText' in field) {
        field.setText(item.value)
      } else if (item.value !== undefined && 'select' in field) {
        field.select(item.value)
      }
    } catch {
      /* missing/unsupported field: preserve the rest of the document */
    }
  }
}

export { addAnnotation, applyFormValues }
